### ISSUE TITLE
Is this plugin bannable?

### ISSUE THREAD

**Issue by Vic3x** [respecting/NitroPerks#11]
The title says everything: Is this plugin bannable?
I'm not concerned about emojis, as they're gifs and can be used everywhere but how about screensharing? How does it work? It should be an only Nitro perk and the fact that it actually works makes me a bit worried. I haven't tried the custom PFP yet but it also seems a bannable thing.

**Comment by Hop1337** [comment]
It seems bannable, but im not sure. As its client side, no one other than you will be able to see the animated profile picture (if its even a thing) or emotes that you send in chat. For it being probably client side, i dont think its bannable

**Comment by Hop1337** [comment]
Just tested the emotes, the plugin is not client side. What the plugin does is:
You click on the emote, it sends the link to the emote image/gif, that automatically becomes a image or a gif. It is not "nitro" but you can "use" emotes for free. About the status it doesnt work sadly. I did not test the profile picture but its unlikely to work.

**Comment by KNIF** [comment]
As far as I know the PFP and the Emotes are not bannable.

The PFP is only client-side so they can't do anything about that and it does not replace buying Nitro for the animated PFP that everyone can see.
The emotes are bannable in theory but as the plugin just sends the link to the Discord CDN with the emotes as a GIF I don't think they'll ban you because of it as you could theoretically do the same without a plugin.
The screenshare is not bannable at the moment as they can/do not detect it (yet). I can imagine that they will fix it and make it server-sided so you can't bypass it in the future.

If you should get banned you'll probably get banned for using BetterDiscord, not because of this plugin specifically.

**Comment by Vic3x** [comment]
Thanks guys for the help
